CLJS-2604: Make build script more robust when recent git tags are missing

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -26,13 +26,25 @@ CLJS_SCRIPT_MVN_OPTS=${CLJS_SCRIPT_MVN_OPTS:-""}
 # if the tag is v0.0.1).
 MAJOR="1"
 MINOR="10"
-REVISION=`git --no-replace-objects describe --match v$MAJOR.$MINOR`
 
-# Extract the version number from the string.
-REVISION_REGEX="v[0-9]*\.[0-9]*-([0-9]*)-.*"
-if [[ $REVISION =~ $REVISION_REGEX ]]
-then
-  REVISION="${BASH_REMATCH[1]}"
+set +e
+REVISION=`git --no-replace-objects describe --match v$MAJOR.$MINOR`
+set -e
+
+if [[ -z "$REVISION" ]]; then
+  echo "WARNING: We were unable to determine revision number from ClojureScript git repo.
+         Please make sure you have recent git tags present in the repo, specifically the tag 'v$MAJOR.$MINOR'.
+         You might consider running:
+         
+           git fetch --tags https://github.com/clojure/clojurescript.git"
+  REVISION="0"
+else 
+  # Extract the version number from the string.
+  REVISION_REGEX="v[0-9]*\.[0-9]*-([0-9]*)-.*"
+  if [[ $REVISION =~ $REVISION_REGEX ]]
+  then
+    REVISION="${BASH_REMATCH[1]}"
+  fi
 fi
 
 TAG=r$MAJOR.$MINOR.$REVISION
